/* Koinly website / self-contained demonstration. No network calls, no real user data. */
(() => {
  'use strict';
  const config = window.KOINLY_SITE || {};
  const STORAGE_KEY = 'koinly-public-demo-v1';
  const viewNames = {dashboard:'Dashboard',transactions:'Transactions',budgets:'Budgets',analytics:'Analytics',plans:'Plan',subscriptions:'Subscriptions',notes:'Notes'};
  const icons = {
    home:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m8 12 4-4 4 4m-4-4v9"/>',
    arrows:'<path d="M4 7h16m-5-4 5 4-5 4M20 17H4m5-4-5 4 5 4"/>',
    target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
    chart:'<path d="M3 3v18h18M7 16l4-5 4 2 5-7"/>',
    bag:'<rect x="4" y="8" width="16" height="13" rx="2"/><path d="M9 9V7a3 3 0 0 1 6 0v2"/>',
    repeat:'<path d="m17 2 4 4-4 4M3 11V9a3 3 0 0 1 3-3h15m-14 16-4-4 4-4m14-1v2a3 3 0 0 1-3 3H3"/>',
    note:'<path d="M5 3h14a2 2 0 0 1 2 2v14l-5 3H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm2 5h10M7 12h8M7 16h5"/>'
  };
  const palette = {Food:'#70e5ae',Transport:'#80bfff',Shopping:'#cbb5ff',Entertainment:'#f6bb82',Bills:'#f38fa8',Other:'#99c2ac'};
  let selectedView = 'dashboard';
  let txFilter = 'all';
  let txSearch = '';
  let state;
  let previousFocus;
  let toastTimer;
  const demoRoot = document.getElementById('demo-app');
  const content = document.getElementById('demo-content');
  const modalRoot = document.getElementById('modal-root');
  const today = () => localDate(new Date());
  function localDate(date){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
  function daysAgo(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-days);return localDate(d);}
  const unique = () => (typeof crypto!=='undefined' && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`);
  const money = amount => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(amount)||0);
  const esc = str => String(str==null?'':str).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isMonth = date => typeof date==='string' && date.slice(0,7)===today().slice(0,7);
  const dateLabel = date => {const d=new Date(`${date}T12:00:00`);return Number.isNaN(d.valueOf())? 'Unknown date': new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(d);};
  const accountName = id => (state.accounts.find(a=>a.id===id)||{}).name||'Account';
  const category = tx => tx.type==='income'?'Income':tx.type==='transfer'?'Transfer':tx.category;
  function baseState(){return {
    accounts:[{id:'bank',name:'Everyday bank',kind:'Bank account',opening:1330},{id:'cash',name:'Cash',kind:'Cash account',opening:215},{id:'savings',name:'Savings',kind:'Savings account',opening:7800}],
    transactions:[
      {id:'seed-salary',title:'Salary',type:'income',category:'Income',amount:3200,accountId:'bank',date:daysAgo(6)},
      {id:'seed-grocery',title:'Groceries',type:'expense',category:'Food',amount:72,accountId:'bank',date:daysAgo(1)},
      {id:'seed-coffee',title:'Morning coffee',type:'expense',category:'Food',amount:6.5,accountId:'cash',date:daysAgo(0)},
      {id:'seed-transport',title:'Transport',type:'expense',category:'Transport',amount:18,accountId:'cash',date:daysAgo(3)},
      {id:'seed-transfer',title:'Move to savings',type:'transfer',category:'Transfer',amount:450,accountId:'bank',toAccountId:'savings',date:daysAgo(5)},
      {id:'seed-freelance',title:'Freelance project',type:'income',category:'Income',amount:480,accountId:'bank',date:daysAgo(2)},
      {id:'seed-sub',title:'Music subscription',type:'expense',category:'Entertainment',amount:12,accountId:'bank',date:daysAgo(12)},
      {id:'seed-dining',title:'Dinner out',type:'expense',category:'Food',amount:43.5,accountId:'bank',date:daysAgo(9)}
    ],
    budgets:{Food:300,Transport:120,Shopping:240,Entertainment:100},
    plans:[{id:'plan-1',name:'Wireless headphones',price:160,category:'Shopping',purchased:false},{id:'plan-2',name:'Weekend getaway',price:420,category:'Entertainment',purchased:false}],
    subscriptions:[{id:'sub-1',name:'Music subscription',price:12,category:'Entertainment',frequency:'Monthly',accountId:'bank'},{id:'sub-2',name:'Cloud storage',price:4,category:'Bills',frequency:'Monthly',accountId:'bank'}],
    notes:[{id:'note-1',title:'A small money goal',html:'<p>Keep the <b>Food budget</b> in check this month and add a little extra to savings.</p>',date:daysAgo(0)}]
  };}
  function loadState(){try{const value=sessionStorage.getItem(STORAGE_KEY);if(value){const saved=JSON.parse(value);if(saved && saved.version===1 && Array.isArray(saved.transactions) && Array.isArray(saved.accounts) && Array.isArray(saved.plans) && Array.isArray(saved.subscriptions) && Array.isArray(saved.notes) && saved.budgets && typeof saved.budgets==='object') return saved;}}catch(_err){}return {version:1,...baseState()};}
  function save(){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(_err){toast('Demo changes could not be saved in this tab.');}}
  function balances(){const totals=Object.fromEntries(state.accounts.map(a=>[a.id,Number(a.opening)||0]));for(const tx of state.transactions){const amount=Number(tx.amount)||0;if(tx.type==='income' && Object.hasOwn(totals,tx.accountId))totals[tx.accountId]+=amount;if((tx.type==='expense'||tx.type==='transfer') && Object.hasOwn(totals,tx.accountId))totals[tx.accountId]-=amount;if(tx.type==='transfer' && Object.hasOwn(totals,tx.toAccountId))totals[tx.toAccountId]+=amount;}return totals;}
  function monthTx(type){return state.transactions.filter(t=>isMonth(t.date) && (!type || t.type===type));}
  function sumTx(list){return list.reduce((n,t)=>n+(Number(t.amount)||0),0);}
  function spent(cat){return sumTx(monthTx('expense').filter(t=>t.category===cat));}
  function orderedTransactions(transactions){return [...transactions].sort((a,b)=>b.date.localeCompare(a.date)||String(b.id).localeCompare(String(a.id)));}
  function txIcon(t){return `<span class="list-icon ${t.type}">${t.type==='income'?'↙':t.type==='transfer'?'⇄':'↗'}</span>`;}
  function amountHtml(tx){return `<b class="${tx.type==='income'?'positive':''}">${tx.type==='income'?'+':tx.type==='expense'?'−':''}${money(tx.amount)}</b>`;}
  function empty(title,description){return `<div class="demo-empty"><strong>${esc(title)}</strong>${esc(description)}</div>`;}
  function header(title,subtitle,action){return `<div class="demo-hgroup"><div><h3>${title}</h3><p>${subtitle}</p></div>${action||''}</div>`;}
  function stat(title,value,small,cls=''){return `<div class="demo-stat"><div>${title}</div><strong class="${cls}">${value}</strong><small>${small}</small></div>`;}
  function renderDashboard(){const values=balances();const total=Object.values(values).reduce((n,v)=>n+v,0);const income=sumTx(monthTx('income'));const expense=sumTx(monthTx('expense'));const recent=orderedTransactions(state.transactions).slice(0,5);return `${header('Your overview',"See your money at a glance.",'<button type="button" class="demo-primary" data-action="add-transaction">+ Add transaction</button>')}<div class="demo-stat-grid">${stat('TOTAL BALANCE',money(total),'Across all sample accounts')}${stat('INCOME',money(income),'This month','income-color')}${stat('EXPENSES',money(expense),'This month','expense-color')}</div><div class="demo-two-col"><section class="demo-panel"><div class="demo-panel-header"><h4>Recent transactions</h4><button type="button" data-go="transactions">View all →</button></div><div class="demo-list">${recent.length?recent.map(tx=>`<div class="demo-list-row">${txIcon(tx)}<div><strong>${esc(tx.title)}</strong><small>${dateLabel(tx.date)} · ${esc(category(tx))}</small></div>${amountHtml(tx)}</div>`).join(''):empty('No transactions','Try adding one to see your activity.')}</div></section><section class="demo-panel"><div class="demo-panel-header"><h4>Your accounts</h4></div><div class="demo-list">${state.accounts.map(a=>`<div class="demo-list-row"><span class="list-icon ${a.id==='savings'?'transfer':''}">${a.id==='cash'?'◈':a.id==='savings'?'⌁':'▤'}</span><div><strong>${esc(a.name)}</strong><small>${esc(a.kind)}</small></div><b>${money(values[a.id])}</b></div>`).join('')}</div><div style="margin-top:22px"><div class="demo-panel-header"><h4>Budget snapshot</h4><button type="button" data-go="budgets">Manage →</button></div>${Object.entries(state.budgets).slice(0,2).map(([name,limit])=>{const used=spent(name);const ratio=limit>0?used/limit:0;return `<div class="small-progress-art" style="margin:13px 0"><div><b>${esc(name)}</b><span>${money(used)} / ${money(limit)}</span></div><i><span style="width:${Math.min(100,Math.max(0,ratio*100))}%"></span></i></div>`;}).join('')}</div></section></div>`;}
  function renderTransactions(){const filtered=orderedTransactions(state.transactions).filter(tx=>(txFilter==='all'||tx.type===txFilter) && (!txSearch||`${tx.title} ${category(tx)} ${accountName(tx.accountId)}`.toLowerCase().includes(txSearch.toLowerCase())));return `${header('Transactions','Find and manage income, expenses and transfers.','<button type="button" class="demo-primary" data-action="add-transaction">+ New transaction</button>')}<div class="demo-filter-bar"><div class="demo-segmented" aria-label="Transaction type">${[['all','All'],['expense','Expenses'],['income','Income'],['transfer','Transfers']].map(([value,label])=>`<button type="button" data-filter="${value}" aria-pressed="${txFilter===value}">${label}</button>`).join('')}</div><input id="demo-transaction-search" class="demo-search" type="search" value="${esc(txSearch)}" placeholder="Search transactions" aria-label="Search transactions" maxlength="80"></div><section class="demo-panel"><div class="demo-table-wrap"><table class="demo-table"><thead><tr><th>Transaction</th><th>Account</th><th>Date</th><th>Amount</th><th>Actions</th></tr></thead><tbody>${filtered.map(tx=>`<tr><td><div class="tx-title">${esc(tx.title)}</div><div class="tx-category">${esc(category(tx))}</div></td><td>${esc(accountName(tx.accountId))}${tx.type==='transfer'?` → ${esc(accountName(tx.toAccountId))}`:''}</td><td>${dateLabel(tx.date)}</td><td>${amountHtml(tx)}</td><td><div class="demo-inline-actions"><button type="button" class="demo-icon-btn" data-action="edit-transaction" data-id="${esc(tx.id)}" aria-label="Edit ${esc(tx.title)}">Edit</button><button type="button" class="demo-icon-btn" data-action="delete-transaction" data-id="${esc(tx.id)}" aria-label="Delete ${esc(tx.title)}">×</button></div></td></tr>`).join('')}</tbody></table></div>${!filtered.length?empty('Nothing found','Try another filter or create a new transaction.'):''}</section>`;}
  function renderBudgets(){return `${header('Budgets','Set limits that work for you and see what you have left.')}<div class="demo-budgets">${Object.entries(state.budgets).map(([cat,limit])=>{const used=spent(cat);const percent=limit>0?used/limit*100:100;return `<section class="demo-panel"><div class="budget-top"><div><span class="list-icon" style="color:${palette[cat]||palette.Other};">${cat==='Food'?'◉':cat==='Transport'?'↗':cat==='Shopping'?'◇':'✦'}</span><h4>${esc(cat)}</h4><div style="font-size:10px;color:#8ba998">Monthly budget</div></div><button type="button" class="demo-ghost" data-action="edit-budget" data-cat="${esc(cat)}">Edit limit</button></div><div style="font-size:25px;font-weight:800;letter-spacing:-1px;margin-top:20px">${money(used)} <span style="font-size:12px;color:#8ca39b;font-weight:400">/ ${money(limit)}</span></div><div class="budget-progress"><span class="${percent>100?'over':''}" style="width:${Math.min(100,Math.max(0,percent))}%"></span></div><div class="budget-meta"><span>${Math.round(percent)}% used</span><b>${percent>100?money(used-limit)+' over limit':money(limit-used)+' left'}</b></div></section>`;}).join('')}</div><p class="modal-note" style="margin-top:16px">Budget spending updates when you add, edit or delete sample transactions.</p>`;}
  function trendChart(){const series=Array.from({length:7},(_,i)=>{const date=daysAgo(6-i);return {date,day:new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(new Date(`${date}T12:00:00`)),income:sumTx(state.transactions.filter(t=>t.date===date&&t.type==='income')),expense:sumTx(state.transactions.filter(t=>t.date===date&&t.type==='expense'))};});const max=Math.max(1,...series.flatMap(x=>[x.income,x.expense]));const height=150;const baseline=179;const barW=15;return `<div class="demo-chart"><svg viewBox="0 0 560 220" role="img" aria-label="Income and expenses for the last seven days"><path d="M10 179H550M10 114H550M10 49H550" stroke="#345145" stroke-dasharray="4 6" fill="none"/>${series.map((p,i)=>{const x=20+i*77;const incomeH=p.income?Math.max(4,p.income/max*height):0;const expenseH=p.expense?Math.max(4,p.expense/max*height):0;return `<rect x="${x}" y="${baseline-incomeH}" width="${barW+6}" height="${incomeH}" rx="4" fill="#5ce0a9"/><rect x="${x+27}" y="${baseline-expenseH}" width="${barW+6}" height="${expenseH}" rx="4" fill="#faa381"/><text class="chart-label" x="${x+24}" y="202" text-anchor="middle">${p.day}</text>`;}).join('')}</svg></div><div style="display:flex;align-items:center;gap:17px;justify-content:center;color:#94aca0;font-size:10px"><span><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#5ce0a9;margin-right:5px"></i>Income</span><span><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#faa381;margin-right:5px"></i>Expenses</span></div>`;}
  function renderAnalytics(){const income=sumTx(monthTx('income'));const expense=sumTx(monthTx('expense'));const cats=Object.entries(palette).map(([name,color])=>({name,color,value:spent(name)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);const total=cats.reduce((s,v)=>s+v.value,0);let cursor=0;const segments=cats.map(x=>{const start=cursor;cursor+=x.value/total*100;return `${x.color} ${start.toFixed(2)}% ${cursor.toFixed(2)}%`;});return `${header('Analytics','Understand what came in and where it went.')}<div class="demo-stat-grid">${stat('INCOME',money(income),'This month','income-color')}${stat('EXPENSES',money(expense),'This month','expense-color')}${stat('NET',money(income-expense),'Income minus expenses',income-expense>=0?'income-color':'expense-color')}</div><div class="analytics-main"><section class="demo-panel"><h4>Cash flow · last 7 days</h4>${trendChart()}</section><section class="demo-panel"><h4>Spending breakdown</h4>${total>0?`<div class="demo-donut" style="background:conic-gradient(${segments.join(',')})"><div><small>Total spent</small><strong>${money(total)}</strong></div></div>${cats.map(c=>`<div class="category-line"><span>${esc(c.name)}</span><div><span style="width:${c.value/total*100}%;background:${c.color}"></span></div><strong>${money(c.value)}</strong></div>`).join('')}`:empty('No expenses yet','Add an expense to see your breakdown.')}</section></div><p class="modal-note" style="margin-top:14px">In the installed app, Analytics supports PDF, XLSX and TXT reports. Reports are not generated by this browser demo.</p>`;}
  function renderPlans(){return `${header('Your plan','Save up for what matters and turn plans into transactions.','<button type="button" class="demo-primary" data-action="add-plan">+ Add to plan</button>')}<div class="demo-card-list">${state.plans.map(item=>`<article class="demo-item-card"><span class="card-label">${esc(item.category).toUpperCase()} · ${item.purchased?'PURCHASED':'PLANNED'}</span><h4>${esc(item.name)}</h4><p>${item.purchased?'Added to your sample transactions.':'Ready whenever you are.'}</p><div class="card-footer"><strong>${money(item.price)}</strong>${item.purchased?'<span class="card-pill">✓ Purchased</span>':`<button type="button" class="demo-secondary" data-action="buy-plan" data-id="${esc(item.id)}">Buy now →</button>`}</div></article>`).join('')}${!state.plans.length?empty('Nothing planned yet','Add a purchase you have in mind.'):''}</div>`;}
  function renderSubscriptions(){const total=state.subscriptions.filter(s=>s.frequency==='Monthly').reduce((n,s)=>n+Number(s.price),0);return `${header('Subscriptions','Keep recurring spending in sight.','<button type="button" class="demo-primary" data-action="add-subscription">+ Add subscription</button>')}<div class="demo-stat-grid">${stat('MONTHLY ITEMS',state.subscriptions.filter(s=>s.frequency==='Monthly').length,'Monthly recurring items')}${stat('MONTHLY TOTAL',money(total),'For monthly items only')}${stat('ACTIVE PLANS',state.subscriptions.length,'All sample subscriptions')}</div><div class="demo-card-list">${state.subscriptions.map(s=>`<article class="demo-item-card"><span class="card-label">${esc(s.frequency).toUpperCase()} · ${esc(s.category).toUpperCase()}</span><h4>${esc(s.name)}</h4><p>From ${esc(accountName(s.accountId))}. The installed app can create transactions on its schedule.</p><div class="card-footer"><strong>${money(s.price)}</strong><button type="button" class="demo-secondary" data-action="add-sub-now" data-id="${esc(s.id)}">Add now →</button></div></article>`).join('')}${!state.subscriptions.length?empty('No subscriptions yet','Add a recurring item to try the sample.'):''}</div><p class="modal-note" style="margin-top:16px">This demo records a subscription only when you select “Add now”; background scheduling is a feature of the installed app.</p>`;}
  function sanitizeRich(markup){const parsed=document.createElement('template');parsed.innerHTML=String(markup||'').slice(0,20000);const inline=new Set(['B','STRONG','I','EM','S','STRIKE','U','MARK','BR']);const blocks=new Set(['P','DIV','UL','OL','LI']);const clean=node=>{if(node.nodeType===Node.TEXT_NODE)return esc(node.nodeValue);if(node.nodeType!==Node.ELEMENT_NODE)return '';const tag=node.tagName;const children=Array.from(node.childNodes).map(clean).join('');if(tag==='BR')return '<br>';if(tag==='SPAN' && /background-color\s*:/i.test(node.getAttribute('style')||''))return `<mark>${children}</mark>`;if(inline.has(tag))return `<${tag.toLowerCase()}>${children}</${tag.toLowerCase()}>`;if(blocks.has(tag))return `<${tag.toLowerCase()}>${children}</${tag.toLowerCase()}>`;return children;};return Array.from(parsed.content.childNodes).map(clean).join('');}
  function plainRich(html){const elem=document.createElement('div');elem.innerHTML=sanitizeRich(html);return (elem.textContent||'').trim();}
  function renderNotes(){return `${header('Notes','Capture ideas, reminders and goals in one place.','<button type="button" class="demo-primary" data-action="add-note">+ New note</button>')}<div class="demo-card-list">${state.notes.map(note=>`<article class="demo-item-card note-card"><span class="card-label">${dateLabel(note.date).toUpperCase()}</span><h4>${esc(note.title)}</h4><div class="note-preview">${sanitizeRich(note.html)}</div><div class="card-footer"><span style="font-size:10px;color:#749482">SAMPLE NOTE</span><button class="demo-secondary" type="button" data-action="edit-note" data-id="${esc(note.id)}">Open →</button></div></article>`).join('')}${!state.notes.length?empty('No notes yet','Add a thought, a reminder or a money goal.'):''}</div>`;}
  function render(){if(!content)return;const page={dashboard:renderDashboard,transactions:renderTransactions,budgets:renderBudgets,analytics:renderAnalytics,plans:renderPlans,subscriptions:renderSubscriptions,notes:renderNotes}[selectedView];content.innerHTML=(page||renderDashboard)();const crumb=document.getElementById('demo-breadcrumb');if(crumb)crumb.textContent=viewNames[selectedView];document.querySelectorAll('#demo-navigation [data-screen]').forEach(b=>{const active=b.dataset.screen===selectedView;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
  function switchView(name){if(!viewNames[name])return;selectedView=name;render();if(window.matchMedia('(max-width:640px)').matches){const frame=document.getElementById('demo');if(frame)frame.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});}}
  function toast(message){const region=document.getElementById('toast-region');if(!region)return;region.innerHTML=`<div class="toast">${esc(message)}</div>`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{region.innerHTML='';},3300);}
  function closeModal(){if(!modalRoot.firstElementChild)return;modalRoot.innerHTML='';document.body.style.overflow='';if(previousFocus && previousFocus.isConnected)previousFocus.focus();}
  function openModal(title,hint,formMarkup,wide=false){previousFocus=document.activeElement;modalRoot.innerHTML=`<div class="modal-backdrop" data-backdrop><section class="modal ${wide?'modal-wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-heading"><button type="button" class="modal-close-x" data-dismiss aria-label="Close">×</button><h3 class="modal-title" id="modal-heading">${title}</h3><p class="modal-hint">${hint}</p>${formMarkup}</section></div>`;document.body.style.overflow='hidden';const first=modalRoot.querySelector('input,textarea,select,[contenteditable],button:not([data-dismiss])');(first||modalRoot.querySelector('[data-dismiss]')).focus();}
  function actions(label='Save'){return `<div class="modal-error" id="modal-error" role="alert"></div><div class="modal-actions"><button type="button" class="demo-ghost" data-dismiss>Cancel</button><button type="submit" class="demo-primary">${label}</button></div>`;}
  function options(values,selected){return values.map(v=>`<option value="${esc(v.id||v)}" ${(v.id||v)===selected?'selected':''}>${esc(v.name||v)}</option>`).join('');}
  function accountsSelect(name,selected){return `<select name="${name}" required>${options(state.accounts,selected||'bank')}</select>`;}
  function formError(form,message){const el=form.querySelector('#modal-error');if(el)el.textContent=message;else toast(message);}
  function openTransaction(id){const tx=id?state.transactions.find(t=>t.id===id):null;const type=tx?.type||'expense';openModal(tx?'Edit transaction':'New transaction','Try tracking a sample transaction. It will update your demo dashboard, budgets and analytics.',`<form id="form-transaction" data-id="${esc(id||'')}"><div class="modal-grid"><div class="field full"><label for="tx-title">Title</label><input id="tx-title" name="title" maxlength="70" required value="${esc(tx?.title||'')}" placeholder="e.g. Lunch"></div><div class="field"><label for="tx-type">Type</label><select id="tx-type" name="type"><option value="expense" ${type==='expense'?'selected':''}>Expense</option><option value="income" ${type==='income'?'selected':''}>Income</option><option value="transfer" ${type==='transfer'?'selected':''}>Transfer</option></select></div><div class="field"><label for="tx-amount">Amount (USD)</label><input id="tx-amount" name="amount" type="number" inputmode="decimal" min="0.01" max="9999999" step="0.01" required value="${tx?Number(tx.amount):''}" placeholder="0.00"></div><div class="field" id="tx-category-field"><label for="tx-category">Category</label><select id="tx-category" name="category">${options(['Food','Transport','Shopping','Entertainment','Bills','Other','Income'],tx?.category||(type==='income'?'Income':'Food'))}</select></div><div class="field"><label for="tx-date">Date</label><input id="tx-date" name="date" type="date" required value="${esc(tx?.date||today())}"></div><div class="field"><label for="tx-account">From / to account</label>${accountsSelect('accountId',tx?.accountId)}</div><div class="field" id="tx-to-account-field"><label for="tx-to-account">Destination</label>${accountsSelect('toAccountId',tx?.toAccountId||'savings')}</div></div>${actions(tx?'Save changes':'Add transaction')}</form>`);updateTransactionType(type);}
  function updateTransactionType(type){const categoryField=document.getElementById('tx-category-field');const toField=document.getElementById('tx-to-account-field');if(categoryField){categoryField.hidden=type==='transfer';const select=categoryField.querySelector('select');if(type==='income')select.value='Income';if(type==='expense'&&select.value==='Income')select.value='Food';}if(toField)toField.hidden=type!=='transfer';}
  function deleteTransaction(id){const tx=state.transactions.find(t=>t.id===id);if(!tx)return;openModal('Delete transaction?',`Remove “${esc(tx.title)}” from your demo. This only changes the fictional sample.`,`<form id="form-delete-tx" data-id="${esc(id)}">${actions('Delete transaction')}</form>`);}
  function openBudget(cat){openModal(`Edit ${esc(cat)} budget`,'Set the monthly sample limit. Spending will recalculate from your transactions.',`<form id="form-budget" data-cat="${esc(cat)}"><div class="field"><label for="budget-limit">Monthly limit (USD)</label><input id="budget-limit" name="limit" type="number" min="1" max="9999999" step="1" required value="${Number(state.budgets[cat])}"></div>${actions('Save budget')}</form>`);}
  function openPlan(){openModal('Add a purchase plan','Create a fictional planned item and try buying it from a sample account.',`<form id="form-plan"><div class="field"><label for="plan-name">Item name</label><input id="plan-name" maxlength="75" name="name" required placeholder="e.g. New keyboard"></div><div class="modal-grid"><div class="field"><label for="plan-price">Price (USD)</label><input id="plan-price" type="number" min="0.01" max="9999999" step="0.01" name="price" required placeholder="0.00"></div><div class="field"><label for="plan-category">Category</label><select id="plan-category" name="category">${options(['Shopping','Entertainment','Food','Transport','Other'],'Shopping')}</select></div></div>${actions('Add to plan')}</form>`);}
  function buyPlan(id){const p=state.plans.find(p=>p.id===id&&!p.purchased);if(!p)return;openModal('Buy planned item',`This will add a ${money(p.price)} sample expense for “${esc(p.name)}”.`,`<form id="form-buy-plan" data-id="${esc(id)}"><div class="field"><label for="buy-account">Pay from</label>${accountsSelect('accountId','bank')}</div>${actions('Confirm purchase')}</form>`);}
  function openSubscription(){openModal('Add a subscription','Create a fictional recurring item. In this demo, you can manually record it with Add now.',`<form id="form-subscription"><div class="field"><label for="sub-name">Subscription name</label><input id="sub-name" name="name" maxlength="75" placeholder="e.g. Streaming service" required></div><div class="modal-grid"><div class="field"><label for="sub-price">Price (USD)</label><input id="sub-price" name="price" type="number" inputmode="decimal" min="0.01" max="9999999" step="0.01" placeholder="0.00" required></div><div class="field"><label for="sub-frequency">Repeats</label><select id="sub-frequency" name="frequency">${options(['Monthly','Weekly','Yearly','Daily'],'Monthly')}</select></div><div class="field"><label for="sub-category">Category</label><select id="sub-category" name="category">${options(['Entertainment','Bills','Food','Transport','Other'],'Bills')}</select></div><div class="field"><label for="sub-account">Spending account</label>${accountsSelect('accountId','bank')}</div></div>${actions('Add subscription')}</form>`);}
  function recordSubscription(id){const sub=state.subscriptions.find(s=>s.id===id);if(!sub)return;state.transactions.unshift({id:unique(),title:sub.name,type:'expense',category:sub.category,amount:Number(sub.price),accountId:sub.accountId,date:today()});save();render();toast(`${sub.name} recorded as a sample expense.`);}
  function openNote(id){const note=id?state.notes.find(n=>n.id===id):null;openModal(note?'Edit note':'New note','Select text, then try bold, italic, strikethrough or highlight. This is sample content only.',`<form id="form-note" data-id="${esc(id||'')}"><div class="field"><label for="note-title">Title</label><input id="note-title" name="title" maxlength="80" required value="${esc(note?.title||'')}" placeholder="What's on your mind?"></div><div class="field"><label id="note-content-label">Note</label><div class="note-toolbar" aria-label="Note formatting"><button type="button" data-format="bold" aria-label="Bold"><b>B</b></button><button type="button" data-format="italic" aria-label="Italic"><i>I</i></button><button type="button" data-format="strikeThrough" aria-label="Strikethrough"><s>S</s></button><button type="button" data-format="hiliteColor" aria-label="Highlight"><span style="background:#5ba170;padding:2px">H</span></button></div><div id="note-rich" role="textbox" aria-multiline="true" aria-labelledby="note-content-label" class="note-editor" contenteditable="true" data-placeholder="A quick thought…">${sanitizeRich(note?.html||'')}</div></div>${actions(note?'Save note':'Create note')}</form>`,true);}
  function resetDemo(){openModal('Start the demo over?','This restores all original sample accounts, transactions, plans, subscriptions, budgets and notes.',`<form id="form-reset-demo">${actions('Reset demo')}</form>`);}
  function validAmount(form,name){const field=form.elements.namedItem(name);const amount=Number(field?.value);return Number.isFinite(amount)&&amount>0&&amount<=9999999?Math.round(amount*100)/100:null;}
  function handleForm(e){const form=e.target;if(!form.id||!form.id.startsWith('form-'))return;e.preventDefault();if(!form.reportValidity())return;const fd=new FormData(form);const id=form.dataset.id;switch(form.id){
    case 'form-transaction':{const amount=validAmount(form,'amount');if(!amount)return formError(form,'Enter an amount greater than zero.');const type=String(fd.get('type'));const accountId=String(fd.get('accountId'));const toAccountId=String(fd.get('toAccountId'));if(type==='transfer' && accountId===toAccountId)return formError(form,'Choose two different accounts for a transfer.');const value={id:id||unique(),title:String(fd.get('title')).trim().slice(0,70),type,category:type==='income'?'Income':type==='transfer'?'Transfer':String(fd.get('category')),amount,accountId,date:String(fd.get('date')),...(type==='transfer'?{toAccountId}:{})};if(!value.title)return formError(form,'Enter a transaction title.');if(id){const i=state.transactions.findIndex(t=>t.id===id);if(i===-1)return;state.transactions[i]=value;}else state.transactions.unshift(value);save();closeModal();render();toast(id?'Transaction updated.':'Transaction added to the demo.');break;}
    case 'form-delete-tx':state.transactions=state.transactions.filter(t=>t.id!==id);save();closeModal();render();toast('Sample transaction deleted.');break;
    case 'form-budget':{const val=validAmount(form,'limit');if(!val)return formError(form,'Enter a positive monthly limit.');state.budgets[form.dataset.cat]=val;save();closeModal();render();toast('Sample budget updated.');break;}
    case 'form-plan':{const price=validAmount(form,'price');if(!price)return formError(form,'Enter a valid price.');const name=String(fd.get('name')).trim();if(!name)return formError(form,'Enter an item name.');state.plans.unshift({id:unique(),name:name.slice(0,75),price,category:String(fd.get('category')),purchased:false});save();closeModal();render();toast('Added to your sample plan.');break;}
    case 'form-buy-plan':{const plan=state.plans.find(p=>p.id===id&&!p.purchased);if(!plan)return;plan.purchased=true;state.transactions.unshift({id:unique(),title:plan.name,type:'expense',category:plan.category,amount:plan.price,accountId:String(fd.get('accountId')),date:today()});save();closeModal();render();toast('Purchase recorded in sample transactions.');break;}
    case 'form-subscription':{const price=validAmount(form,'price');if(!price)return formError(form,'Enter a valid subscription price.');const name=String(fd.get('name')).trim();if(!name)return formError(form,'Enter a subscription name.');state.subscriptions.unshift({id:unique(),name:name.slice(0,75),price,frequency:String(fd.get('frequency')),category:String(fd.get('category')),accountId:String(fd.get('accountId'))});save();closeModal();render();toast('Sample subscription added.');break;}
    case 'form-note':{const title=String(fd.get('title')).trim();if(!title)return formError(form,'Enter a note title.');const html=sanitizeRich(document.getElementById('note-rich')?.innerHTML||'');if(!plainRich(html))return formError(form,'Enter some note text.');if(plainRich(html).length>5000)return formError(form,'Keep sample notes under 5,000 characters.');if(id){const i=state.notes.findIndex(n=>n.id===id);if(i===-1)return;state.notes[i]={...state.notes[i],title:title.slice(0,80),html,date:today()};}else state.notes.unshift({id:unique(),title:title.slice(0,80),html,date:today()});save();closeModal();render();toast(id?'Sample note saved.':'Sample note created.');break;}
    case 'form-reset-demo':state={version:1,...baseState()};txFilter='all';txSearch='';selectedView='dashboard';save();closeModal();render();toast('Demo restored to its original sample data.');break;
  }}
  function handleClick(e){const dismiss=e.target.closest('[data-dismiss]');if(dismiss){closeModal();return;}if(e.target.hasAttribute('data-backdrop')){closeModal();return;}const nav=e.target.closest('#demo-navigation [data-screen]');if(nav){switchView(nav.dataset.screen);return;}const go=e.target.closest('[data-go]');if(go){switchView(go.dataset.go);return;}const filter=e.target.closest('[data-filter]');if(filter){txFilter=filter.dataset.filter;render();return;}const action=e.target.closest('[data-action]');if(!action)return;switch(action.dataset.action){case 'add-transaction':openTransaction();break;case 'edit-transaction':openTransaction(action.dataset.id);break;case 'delete-transaction':deleteTransaction(action.dataset.id);break;case 'edit-budget':openBudget(action.dataset.cat);break;case 'add-plan':openPlan();break;case 'buy-plan':buyPlan(action.dataset.id);break;case 'add-subscription':openSubscription();break;case 'add-sub-now':recordSubscription(action.dataset.id);break;case 'add-note':openNote();break;case 'edit-note':openNote(action.dataset.id);break;}}
  function handleKey(e){if(!modalRoot.firstElementChild)return;if(e.key==='Escape'){e.preventDefault();closeModal();return;}if(e.key!=='Tab')return;const focusable=Array.from(modalRoot.querySelectorAll('button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[contenteditable=true]')).filter(el=>el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
  function enableNoteToolbar(){let lastSelection=null;let restoring=false;document.addEventListener('selectionchange',()=>{if(restoring || !window.getSelection)return;const editor=modalRoot.querySelector('#note-rich');const selection=window.getSelection();if(editor && selection && selection.rangeCount && editor.contains(selection.anchorNode))lastSelection=selection.getRangeAt(0).cloneRange();});modalRoot.addEventListener('pointerdown',e=>{if(e.target.closest('[data-format]'))e.preventDefault();});modalRoot.addEventListener('mousedown',e=>{if(e.target.closest('[data-format]'))e.preventDefault();});modalRoot.addEventListener('click',e=>{const button=e.target.closest('[data-format]');if(!button)return;const editor=modalRoot.querySelector('#note-rich');if(!editor)return;restoring=true;editor.focus();if(lastSelection && editor.contains(lastSelection.startContainer) && editor.contains(lastSelection.endContainer) && window.getSelection){const selection=window.getSelection();selection.removeAllRanges();selection.addRange(lastSelection);}if(button.dataset.format==='hiliteColor')document.execCommand('hiliteColor',false,'#5ba170');else document.execCommand(button.dataset.format,false,null);const current=window.getSelection?.();if(current && current.rangeCount && editor.contains(current.anchorNode))lastSelection=current.getRangeAt(0).cloneRange();restoring=false;});}
  function initSite(){const menu=document.getElementById('mobile-menu');menu?.addEventListener('click',()=>{const nav=document.getElementById('site-nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});document.querySelectorAll('#site-nav a').forEach(el=>el.addEventListener('click',()=>{document.getElementById('site-nav').classList.remove('open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Open navigation');}));document.getElementById('year').textContent=String(new Date().getFullYear());const github=document.getElementById('github-link');if(github && /^https:\/\//.test(config.githubUrl||'')){github.href=config.githubUrl;github.hidden=false;}const listings=[['play-store-slot',config.googlePlayUrl,'Get it on'],['microsoft-store-slot',config.microsoftStoreUrl,'Get it from']];for(const [id,url,label] of listings){if(!/^https:\/\//.test(url||''))continue;const old=document.getElementById(id);if(!old)continue;const a=document.createElement('a');a.id=id;a.className='store-slot store-link';a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.innerHTML=old.innerHTML;a.querySelector('small').textContent=label.toUpperCase();old.replaceWith(a);}}
  function initDemo(){state=loadState();document.querySelectorAll('[data-icon]').forEach(el=>{if(icons[el.dataset.icon])el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[el.dataset.icon]}</svg>`;});document.addEventListener('click',handleClick);document.addEventListener('submit',handleForm);document.addEventListener('keydown',handleKey);document.addEventListener('change',e=>{if(e.target.id==='tx-type')updateTransactionType(e.target.value);});document.addEventListener('input',e=>{if(e.target.id==='demo-transaction-search'){const position=e.target.selectionStart;txSearch=e.target.value;render();const newInput=document.getElementById('demo-transaction-search');newInput?.focus();if(newInput && typeof position==='number')newInput.setSelectionRange(position,position);}});document.getElementById('reset-demo')?.addEventListener('click',resetDemo);enableNoteToolbar();render();}
  initSite();if(demoRoot)initDemo();
})();
